- hosts: servers

  tasks:

    - name: Stop old container
      command: docker stop ticket-container
      ignore_errors: yes

    - name: Remove old container
      command: docker rm ticket-container
      ignore_errors: yes

    - name: Pull latest Docker image
      command: docker pull blanck21/ticket-reservation:latest

    - name: Run container
      command: docker run -d -p 2080:8080 --name ticket-container blanck21/ticket-reservation:latest