- hosts: servers
  tasks:

    - name: Stop old container
      shell: docker stop ticket-container
      ignore_errors: yes

    - name: Remove old container
      shell: docker rm ticket-container
      ignore_errors: yes

    - name: Pull Docker Image
      shell: docker pull blanck21/ticket-reservation

    - name: Run Container
      shell: docker run -d -p 2080:8080 --name ticket-container blanck21/ticket-reservation